# Generated by Django 6.1.1 on 2026-09-16 15:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consumers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_period', models.CharField(max_length=20)),
                ('previous_reading', models.DecimalField(decimal_places=3, max_digits=12)),
                ('current_reading', models.DecimalField(decimal_places=3, max_digits=12)),
                ('consumption_kwh', models.DecimalField(decimal_places=3, default=Decimal('0.00'), max_digits=12)),
                ('tariff_rate', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('ISSUED', 'Выставлен'), ('PAID', 'Оплачен'), ('OVERDUE', 'Просрочен')], default='ISSUED', max_length=20)),
                ('due_date', models.DateField()),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='consumers.consumer')),
            ],
            options={
                'verbose_name': 'Счёт',
                'verbose_name_plural': 'Счета',
                'ordering': ['-billing_period', '-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('CASH', 'Наличные'), ('CARD', 'Карта'), ('TRANSFER', 'Перевод')], default='TRANSFER', max_length=20)),
                ('reference', models.CharField(max_length=80, unique=True)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.invoice')),
            ],
            options={
                'verbose_name': 'Платёж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['-paid_at'],
            },
        ),
    ]
