# Generated by Django 6.1.1 on 2026-09-16 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('consumers', '0004_consumptionanomaly'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tariff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price_per_kwh', models.DecimalField(decimal_places=4, max_digits=10)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Тариф',
                'verbose_name_plural': 'Тарифы',
                'ordering': ['-valid_from', 'name'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='consumers.contract'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='price_per_kwh_snapshot',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tariff_name_snapshot',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('ISSUED', 'Выставлен'), ('PARTIALLY_PAID', 'Частично оплачен'), ('PAID', 'Оплачен'), ('OVERDUE', 'Просрочен')], default='ISSUED', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('contract', 'billing_period'), name='unique_contract_billing_period'),
        ),
    ]
