# Generated by Django 6.1.1 on 2026-09-16 16:43

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='meter-readings/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='recognition_confidence',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='recognized_value',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='review_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Вручную'), ('PHOTO', 'Фотография'), ('CAMERA', 'Камера'), ('EMPLOYEE', 'Сотрудник')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Подтверждено'), ('PENDING_REVIEW', 'Ожидает проверки'), ('REJECTED', 'Отклонено')], default='CONFIRMED', max_length=20),
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=80, unique=True)),
                ('model_name', models.CharField(blank=True, max_length=120)),
                ('meter_type', models.CharField(default='Электросчетчик', max_length=80)),
                ('install_date', models.DateField()),
                ('commissioning_reading', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('multiplier', models.DecimalField(decimal_places=3, default=Decimal('1.000'), max_digits=8)),
                ('phase_count', models.PositiveSmallIntegerField(default=1)),
                ('status', models.CharField(choices=[('ACTIVE', 'Активен'), ('REPLACED', 'Заменен'), ('RETIRED', 'Выведен из эксплуатации')], default='ACTIVE', max_length=20)),
                ('replaced_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_meters', to='consumers.meter')),
            ],
            options={
                'verbose_name': 'Прибор учета',
                'verbose_name_plural': 'Приборы учета',
                'ordering': ['serial_number'],
            },
        ),
        migrations.AddField(
            model_name='meterreading',
            name='meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readings', to='consumers.meter'),
        ),
        migrations.CreateModel(
            name='SupplyObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('object_type', models.CharField(default='Жилой объект', max_length=80)),
                ('area_m2', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('residents_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('ACTIVE', 'Активен'), ('SUSPENDED', 'Приостановлен'), ('CLOSED', 'Закрыт')], default='ACTIVE', max_length=20)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supply_objects', to='consumers.consumer')),
            ],
            options={
                'verbose_name': 'Объект потребления',
                'verbose_name_plural': 'Объекты потребления',
                'ordering': ['address'],
            },
        ),
        migrations.AddField(
            model_name='meter',
            name='supply_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meters', to='consumers.supplyobject'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Действует'), ('SUSPENDED', 'Приостановлен'), ('CLOSED', 'Закрыт')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='consumers.consumer')),
                ('supply_object', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contracts', to='consumers.supplyobject')),
            ],
            options={
                'verbose_name': 'Договор',
                'verbose_name_plural': 'Договоры',
                'ordering': ['-start_date', 'number'],
            },
        ),
    ]
