# Generated by Django 6.1.1 on 2026-09-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0002_meterreading_confirmed_at_meterreading_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meterreading',
            name='photo_checksum',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='meterreading',
            name='photo_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
