# Generated by Django 6.1.1 on 2026-09-16 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consumers', '0003_meterreading_photo_checksum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumptionAnomaly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.DateField()),
                ('anomaly_score', models.DecimalField(decimal_places=5, max_digits=8)),
                ('anomaly_type', models.CharField(default='CONSUMPTION', max_length=80)),
                ('description', models.TextField()),
                ('model_version', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('NEW', 'Новое'), ('REVIEWING', 'На проверке'), ('CONFIRMED', 'Подтверждено'), ('REJECTED', 'Отклонено')], default='NEW', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('review_comment', models.TextField(blank=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumption_anomalies', to='consumers.consumer')),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumption_anomalies', to='consumers.meter')),
                ('reading', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anomalies', to='consumers.meterreading')),
            ],
            options={
                'verbose_name': 'Аномалия потребления',
                'verbose_name_plural': 'Аномалии потребления',
                'ordering': ['-detected_at'],
            },
        ),
    ]
